name: shared_preferences_settings
description: Settings Screen with Custom Shared Preference Interface
author: Harshvardhan Joshi<hj2931996@gmail.com>
repository: https://github.com/GAM3RG33K/shared_preferences_settings
documentation: https://github.com/GAM3RG33K/shared_preferences_settings
homepage: https://github.com/GAM3RG33K/shared_preferences_settings

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # library for RxDart functions
  rxdart: ^0.22.6
  # library for showing a color picker
  flutter_colorpicker: ^0.2.6

  #library to access storage directories
  path_provider: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
